
-- Database Creation
CREATE DATABASE shopkart;
USE shopkart;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  img_src VARCHAR(255) NOT NULL
);
